#pragma once

#define SQURE_SHAPE_TYPE 1
#define STRAIGHT_TYPE 2
#define T_SHPAE_TYPE 3
#define Z_SHAPE_TYPE 4
#define L_SHAPE_TYPE 5

#define NORMAL_CARD_COST 2
#define UPGRADE_CARD_COST 3
#define SPECIAL_CARD_COST 4

#define PLAYER_DECK_NUMBER 8
#define USER_COST 6
#define PLAYER_TURN 5