#pragma once

#define WIDTH_TYPE 1
#define LENGTH_TYPE 2
#define DOT_TYPE 3

#define X_TYPE 4
#define LONG_WIDTH_TYPE 5
#define LONG_LENGTH-TYPE 6
#define SQURE_TYPE 7

#define PLAYER_DECK_NUMBER 13

#define PLAYER_STAGE1_TURN 4
#define PLAYER_STAGE2_TURN 7
#define PLAYER_STAGE3_TURN 6
#define PLAYER_STAGE4_TURN 8
#define PLAYER_STAGE5_TURN 7
#define PLAYER_STAGE6_TURN 7
#define PLAYER_STAGE7_TURN 10
#define PLAYER_STAGE8_TURN 8
#define PLAYER_STAGE9_TURN 11
