#pragma once
enum CardType {
    WIDTH_TYPE = 1,
    LENGTH_TYPE = 2,
    DOT_TYPE = 3,
    X_TYPE = 4,
    LONG_WIDTH_TYPE = 5,
    LONG_LENGTH_TYPE = 6,
    SQUARE_TYPE = 7,
    PURIFICATION_TYPE = 8,
    CROSS_TYPE = 9,
    PURIFICATION_CROSS_TYPE = 10,
    UPGRADE_SQUARE_TYPE = 11,
    UPGRADE_X_TYPE = 12,
    UPGRADE_CROSS_TYPE = 13,
    HELLFIRE_TYPE = 14,
};
//초기 플레이어 덱 카드 수
#define INIT_PLAYER_DECK_NUMBER 13

#define PLAYER_STAGE1_TURN 4
#define PLAYER_STAGE2_TURN 7
#define PLAYER_STAGE3_TURN 6
#define PLAYER_STAGE4_TURN 8
#define PLAYER_STAGE5_TURN 7
#define PLAYER_STAGE6_TURN 7
#define PLAYER_STAGE7_TURN 10
#define PLAYER_STAGE8_TURN 8
#define PLAYER_STAGE9_TURN 11
